include: package:lint/strict.yaml

linter:
  rules:
    sort_pub_dependencies: false
    prefer_single_quotes: true
    prefer_relative_imports: true
    always_use_package_imports: false

analyzer:
  exclude:
    - "**.g.dart"
    - "**.freezed.dart"
  errors:
    missing_return: error
    missing_required_param: error
    parameter_assignments: error
    todo: info
