name: student_planner
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.4"

dependencies:
  bloc: ^8.1.2
  cupertino_icons: ^1.0.5
  drift: ^2.8.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_colorpicker: ^1.0.3
  flutter_local_notifications: ^14.1.1
  flutter_material_color_picker: ^1.2.0
  flutter_timezone: ^1.0.6
  freezed_annotation: ^2.2.0
  gap: ^3.0.0
  intl: ^0.18.1
  json_annotation: ^4.8.1
  path: ^1.8.3
  path_provider: ^2.0.15
  provider: ^6.0.4
  sqlite3_flutter_libs: ^0.5.15
  table_calendar: ^3.0.9
  timezone: ^0.9.2

dev_dependencies:
  build_runner: ^2.4.5
  drift_dev: ^2.8.3
  flutter_test:
    sdk: flutter
  freezed: ^2.3.5
  json_serializable: ^6.7.0
  lint: ^2.1.2

flutter:
  uses-material-design: true
