name: student_planner
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"
  flutter: ">=3.3.5"

dependencies:
  bloc: ^8.1.0
  cupertino_icons: ^1.0.2
  drift: ^2.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_material_color_picker: ^1.1.0+2
  freezed_annotation: ^2.2.0
  gap: ^2.0.0
  intl: ^0.17.0
  json_annotation: ^4.7.0
  path: ^1.8.2
  path_provider: ^2.0.0
  provider: ^6.0.4
  sqlite3_flutter_libs: ^0.5.0
  table_calendar: ^3.0.8

dev_dependencies:
  build_runner: ^2.3.2
  drift_dev: ^2.2.0+1
  flutter_test:
    sdk: flutter
  freezed: ^2.2.1
  json_serializable: ^6.5.4
  lint: ^1.10.0

flutter:
  uses-material-design: true
